/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root';
import { Route as WineExplorerImport } from './pages/wine-explorer';
import { Route as IndexImport } from './pages/index';

// Create/Update Routes

const WineExplorerRoute = WineExplorerImport.update({
  id: '/wine-explorer',
  path: '/wine-explorer',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/wine-explorer': {
      id: '/wine-explorer';
      path: '/wine-explorer';
      fullPath: '/wine-explorer';
      preLoaderRoute: typeof WineExplorerImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/wine-explorer': typeof WineExplorerRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/wine-explorer': typeof WineExplorerRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/wine-explorer': typeof WineExplorerRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/wine-explorer';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/wine-explorer';
  id: '__root__' | '/' | '/wine-explorer';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  WineExplorerRoute: typeof WineExplorerRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WineExplorerRoute: WineExplorerRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/wine-explorer"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/wine-explorer": {
      "filePath": "wine-explorer.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
